### ISSUE TITLE
What inline expression can be used to support sharding tables like t_order_[00..99]

### ISSUE THREAD

**Issue by joooohnli** [sharding-sphere/sharding-sphere#1566]
## Question

How to support sharding tables t_order_[00..99] by using inline expression?

I find a way as below:
```
    t_order: 
      actualDataNodes: ds_0.t_order_${0..9}${0..9}
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${"${order_id % 10}".padLeft(2,'0')}
      keyGeneratorColumnName: order_id
```

But, could it be more elegant?
