### ISSUE TITLE
scope of SET SESSION variable in sharding-proxy

### ISSUE THREAD

**Issue by loxp** [sharding-sphere/sharding-sphere#1641]
## Question

config.yaml

```
schemaName: master_slave_db

dataSources:
  master_ds:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_master?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
  slave_ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_slave_0?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50

masterSlaveRule:
  name: ms_ds
  masterDataSourceName: master_ds
  slaveDataSourceNames:
    - slave_ds_0
```

server.yaml

```
authentication:
  username: root
  password: root

props:
  max.connections.size.per.query: 1
  acceptor.size: 16
  executor.size: 16
  proxy.frontend.flush.threshold: 128
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  sql.show: true
```

Sharding-proxy is started using configurations above. Two mysql client are connected to 127.0.0.1:3307, then one client execute SQL:
```
SHOW SESSION variables like '%safe_update%'; -- got OFF
SET SESSION SQL_SAFE_UPDATES = 1;
```

Then another execute SQL:

```
SHOW SESSION variables like '%safe_update%'; -- got ON
```

The SET SQL is SESSION scope, but why other session is affected?
