### ISSUE TITLE
default-table-strategy 如何使用？

### ISSUE THREAD

**Issue by j2eegis** [sharding-sphere/sharding-sphere#979]
### 使用版本是sharding-jdbc 3.0 
```
default-table-strategy:
          inline:
            algorithm-expression:
            sharding-column:  user_id

```
